"""
Constants file
"""

available_leagues_football_leagues = {"1 English Premier League": ["1", "england/premier-league/", 20],
                     "2 English Championship": ["2", "england/championship/", 24],
                     "3 English League One": ["3", "england/league-one/", 24],
                     "4 English League Two": ["4", "england/league-two/", 24],
                     "5 Spanish Primera": ["5", "spain/primera-division/", 20],
                     "6 Spanish Segunda": ["6", "spain/segunda-division/", 22],
                     "7 Spanish Segunda B": ["7", "spain/segunda-b/", 20],
                     "8 French Lique 1": ["8", "france/ligue-1/", 20],
                     "9 French Ligue 2": ["9", "france/ligue-2/", 20],
                     "10 German Bundesliga": ["10", "germany/bundesliga/", 18],
                     "11 German 2 Bundesliga": ["11", "germany/2.-bundesliga/", 18],
                     "12 German Liga": ["12", "germany/3.-liga/", 20],
                     "13 Italian Serie A": ["13", "italy/serie-a/", 20],
                     "14 Italian Serie B": ["14", "italy/serie-b/", 19],
                     "15 Brazillian Serie A": ["15", "brazil/serie-a/", 20],
                     "16 Brazillian Serie B": ["16", "brazil/serie-b/", 20],
                     "17 Argentinian Primera Division": ["17", "argentina/primera-division/", 26],
                     "18 Argentinian Prim B Nacional": ["18", "argentina/prim-b-nacional/", 25],
                     "19 Argentinian Prim B Metro": ["19", "argentina/prim-b-metro/", 20],
                     "20 Scottish Premier": ["20", "scotland/premiership/", 12],
                     "21 Scottish Championship": ["21", "scotland/championship/", 10],
                     "22 Scottish League One": ["22", "scotland/league-one/", 10],
                     "23 Scottish League Two": ["23", "scotland/league-two/", 10],
                     "24 Swiss Super League": ["24", "switzerland/super-league/", 10],
                     "25 Swiss Challenge League": ["25", "switzerland/challenge-league/", 10],
                     "26 Ukranian Premier League": ["26", "ukraine/premier-league/", 12],
                     "27 Ukranian Persha Liga": ["27", "ukraine/persha-liga/", 16],
                     "28 Dutch Eredivisie": ["28", "netherlands/eredivisie/", 18],
                     "29 Dutch Eerste Divisie": ["29", "netherlands/eerste-divisie/", 20],
                     "30 Greek Super League": ["30", "greece/super-league/", 16],
                     "31 Greek Football League": ["31", "greece/football-league/", 18],
                     "32 Czech Liga": ["32", "czech-republic/czech-liga/", 16],
                     "33 Czech FNL": ["33", "czech-republic/fnl/", 16],
                     "34 Russian Premier League": ["34", "russia/premier-league/", 16],
                     "35 Russian FNL": ["35", "russia/fnl/", 20],
                     "36 Turkish Super Lig": ["36", "turkey/super-lig/", 18],
                     "37 Turkish 1 Lig": ["37", "turkey/1.-lig/", 18]
                     }


submenu_options = ["(1) Select a league",
                   "(2) Generate predictions on currently loaded fixtures",
                   "(3) Single game analysis from fixture list*",
                   "(4) Manual single game analysis",
                   "(5) Reports",
                   "(6) Import data from JSON file",
                   "(7) Clear currently loaded league data",
                   "(8) Clear currently stored prediction data",
                   "(M) Previous menu",
                   "\nItems marked with a * are not available in this version."]
